<?
$m=array(
            'memId'=>'memId',
            'HKID'=>'HKID',
            'nickname'=>'nickName',
            'UPDATED'=>'UPDATED',
            'UPDATEDBY'=>'UPDATEDBY',
            'CREATED'=>'CREATED',
            'CREATEDBY'=>'CREATEDBY',
            'DELETED'=>'DELETED',
            'DELETEDBY'=>'DELETEDBY'   
        );